AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 25
  Exclude:
    - lib/ucfg/env_expander.rb
    - lib/ucfg/yaml_loader.rb

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/ucfg/env_expander.rb
    - lib/ucfg/yaml_loader.rb

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 10
